#ifndef __QUASARCONFIG_H__
#define __QUASARCONFIG_H__

// Detection settings
#define QCONF_DETECT_TILE_RESOLUTION 5
#define QCONF_DETECT_TILE_QUANTITY  (QCONF_DETECT_TILE_RESOLUTION * QCONF_DETECT_TILE_RESOLUTION)
#define QCONF_DETECT_TILE_SIZE_X    32
#define QCONF_DETECT_TILE_SIZE_Y    32
#define QCONF_DETECT_TILE_SIZE      (QCONF_DETECT_TILE_SIZE_X * QCONF_DETECT_TILE_SIZE_Y)

// Camera settings
#define QCONF_FRAMERATE      10.0
#define QCONF_EXPOSURE       90E3
#define QCONF_IMAGE_POS_X    570
#define QCONF_IMAGE_POS_Y    430
#define QCONF_IMAGE_FORMAT_X QCONF_DETECT_TILE_SIZE_X
#define QCONF_IMAGE_FORMAT_Y QCONF_DETECT_TILE_SIZE_Y
#define QCONF_IMAGE_SIZE (QCONF_IMAGE_FORMAT_X * QCONF_IMAGE_FORMAT_Y)

#endif /* __QUASARCONFIG_H__ */