#ifndef __QUASARCONFIG_H__
#define __QUASARCONFIG_H__

// Detection settings
#define QCONF_DETECT_TILE_RESOLUTION 3
#define QCONF_DETECT_TILE_QUANTITY (QCONF_DETECT_TILE_RESOLUTION * QCONF_DETECT_TILE_RESOLUTION)

// Camera settings
#define QCONF_FRAMERATE      10.0
#define QCONF_EXPOSURE       60E3
#define QCONF_IMAGE_POS_X    570
#define QCONF_IMAGE_POS_Y    430
#define QCONF_IMAGE_FORMAT_X 125
#define QCONF_IMAGE_FORMAT_Y 125
#define QCONF_IMAGE_SIZE (QCONF_IMAGE_FORMAT_X * QCONF_IMAGE_FORMAT_Y)

#endif /* __QUASARCONFIG_H__ */